### ISSUE TITLE
Broken with hyperterm 0.8

### ISSUE THREAD

**Issue by knownasilya** [patrik-piskay/hyperterm-tabs#6] opened 2016-10-06 15:36 UTC
Tabs just don't work at all, they don't open or show up with this plugin enabled.

**Comment by patrik-piskay** [comment] 2016-10-06 15:40
Hi @knownasilya, I haven't tested it on 0.8 yet, hyperterm has changed quite a bit since the last release. I will test and fix later today, thanks

**Comment by patrik-piskay** [comment] 2016-10-06 21:57
Unfortunately we will have to wait until https://github.com/zeit/hyper/pull/800 gets merged and new version of Hyper is released as it is a blocker.

Until then I'd advise to comment out the `hyperterm-tabs` from plugins

**Comment by patrik-piskay** [comment] 2016-10-10 10:08
I've just released a new version that does nothing (and more importantly, doesn't break anything :)) so you can keep `hyperterm-tabs` in your `hyper.js` config file. Reason for that is that once Hyper is fixed and this package works again, I will release a new version and it will start working for you again. (*Probably should have done that on day1*)

**Comment by knownasilya** [comment] 2016-10-18 15:33
I think the issue has been fixed upstream and released with the latest version.

**Comment by patrik-piskay** [comment] 2016-10-18 15:42
Yep, I am aware of that, I just need to find some time to finish with the changes in this package as the last 2 weeks were busy. Probably tomorrow evening on my flight and during Thursday I'd like to release a fix. Fingers crossed :)

**Comment by mheiber** [comment] 2016-10-26 15:01
@patrik-piskay what do you think of adding keyboard shortcuts to move tabs left/right? That could be a good stop-gap while this issue is being worked-on.

**Comment by knownasilya** [comment] 2016-10-26 15:39
Yes please :) probably more helpful for me.

**Comment by patrik-piskay** [comment] 2016-10-26 21:41
Sounds like a good idea, I'll take a look over the weekend (also on the Hyper issue but I guess even when fixed it will take longer to get a new Hyper release so I think it probably makes sense to invest time to the keyboard shortcuts)

**Comment by luisherranz** [comment] 2016-12-09 09:52
I was about to suggest the very same thing than @mheiber.

Also, maybe a key modifier can be added to the drag and drop, so there's no need for the title-bar. Something like "cmd+alt+drag&drop".

**Comment by patrik-piskay** [comment] 2016-12-12 18:19
Hey guys, with Hyper v1 now out, I'll check what could be done with tabs reordering! I'll update this issue tomorrow/Wednesday.

**Comment by knownasilya** [comment] 2016-12-12 21:09
Woot

**Comment by patrik-piskay** [comment] 2016-12-13 21:32
Keyboard shortcuts implemented in https://github.com/patrik-piskay/hyperterm-tabs/pull/8

`cmd+shift+left/right`

Let me know if you have any issues! (You might need to remove the package from hyper config, save and add it again to force a re-fetch)

I'll update readme soon.

**Comment by mheiber** [comment] 2016-12-14 19:11
@patrik-piskay thank you for implementing this!
The keyboard shortcut doesn't work for me on:
- OS X El Capitan
- Hyper 1.0.0

I also removed the hyperterm-tabs plugin, reloaded, then added it back.
I'm trying `option+shift+left/right` and `fn+option+shift+left/right`.

Thank you for your work on this

**Comment by patrik-piskay** [comment] 2016-12-14 19:30
Hm this is interesting. So it doesn't work with `shift+alt+arrows`? Try the shortcuts after making the term actually active by clicking into it (not on just the tabs section, but actual "body").

**Comment by mheiber** [comment] 2016-12-14 19:42
Still doesn't work. Thanks for the suggestion, though.

**Comment by patrik-piskay** [comment] 2016-12-15 10:21
I can confirm `option+shift+arrows` works for me, the save environment as you @mheiber. Is there anything useful in developer tools' console?

**Comment by patrik-piskay** [comment] 2016-12-16 15:43
Great! Closing this issue, if there are any other issues, let's open specific gh issues for them (like the one for Windows)

**Closed by patrik-piskay** 2016-12-16 15:43 UTC
