### ISSUE TITLE
CSS problems

### ISSUE THREAD

**Issue by luisherranz** [patrik-piskay/hyperterm-tabs#10] opened 2016-12-19 11:48 UTC
When I activate the last version the border of the tab on the left gets messed up.

This is with the plugin deactivated:
![screen shot 2016-12-19 at 12 41 04](https://cloud.githubusercontent.com/assets/3305402/21311720/021f1d98-c5e9-11e6-87e7-70270605abe1.png)
![screen shot 2016-12-19 at 12 40 58](https://cloud.githubusercontent.com/assets/3305402/21311757/4073bbf8-c5e9-11e6-8088-4d9786aac168.png)

And this is with the plugin activated:
![screen shot 2016-12-19 at 12 40 26](https://cloud.githubusercontent.com/assets/3305402/21311784/5b616334-c5e9-11e6-8866-555ed5f762cd.png)
![screen shot 2016-12-19 at 12 40 35](https://cloud.githubusercontent.com/assets/3305402/21311787/5d4e58be-c5e9-11e6-89c0-e618141f5a7d.png)

Hyper 1.0.0 and Mac 10.11

Otherwise it works great by the way :)

**Comment by patrik-piskay** [comment] 2016-12-19 11:55
Thanks @luisherranz. This is caused by Tab styles needed for drag&drop but as drag&drop is not possible for now, I'll disable the styles. I'll update this issue when it's done.

**Comment by luisherranz** [comment] 2016-12-19 12:59
Awesome, thanks!

**Comment by luisherranz** [comment] 2016-12-27 10:59
Is this css?
https://github.com/patrik-piskay/hyperterm-tabs/blob/master/index.js#L12-L43

Do you want me to do a PR?

**Comment by patrik-piskay** [comment] 2016-12-27 11:56
Yep, `hyperterm-tabs` also defines it's own styles, used here https://github.com/patrik-piskay/hyperterm-tabs/blob/master/index.js#L323-L338

PR would be awesome!

**Comment by luisherranz** [comment] 2016-12-28 16:45
There you go: https://github.com/patrik-piskay/hyperterm-tabs/pull/11

**Comment by patrik-piskay** [comment] 2017-01-02 10:22
Released, closing.

**Closed by patrik-piskay** 2017-01-02 10:22 UTC
